// 本地高保真 Mock RSS 数据源
// 用于在国外网络线路请求超时/失败时，提供完美的兜底数据展示，避免界面空白

export const MOCK_RSS_ITEMS = [
  {
    id: "mock1",
    source: "rss",
    sourceLabel: "Autosport",
    sourceCategory: "news",
    tier: "T1",
    weight: 1.25,
    title: "Verstappen warns Red Bull of 'fundamental issues' despite Monaco podium fight",
    url: "https://www.autosport.com/f1/news/verstappen-warns-red-bull-of-fundamental-issues/1061234/",
    publishedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    author: null,
    score: 85,
    comments: 42,
    engagementScore: 169
  },
  {
    id: "mock2",
    source: "rss",
    sourceLabel: "The Race",
    sourceCategory: "news",
    tier: "T1",
    weight: 1.25,
    title: "McLaren tech update: Inside the revised front wing structure for Barcelona GP",
    url: "https://the-race.com/formula-1/mclaren-tech-update-barcelona-front-wing/",
    publishedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    author: null,
    score: 95,
    comments: 28,
    engagementScore: 151
  },
  {
    id: "mock3",
    source: "reddit",
    sourceLabel: "r/F1Technical",
    sourceCategory: "hot",
    tier: "T1.5",
    weight: 1.0,
    title: "Detailed analysis of Ferrari's new sidepod inlets and floor fence orientation",
    url: "https://www.reddit.com/r/F1Technical/comments/detailed_analysis_ferrari_sidepods/",
    publishedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    author: "WindTunnelEngineer",
    score: 140,
    comments: 55,
    engagementScore: 250
  },
  {
    id: "mock4",
    source: "rss",
    sourceLabel: "RaceFans",
    sourceCategory: "news",
    tier: "T1.5",
    weight: 1.0,
    title: "Hamilton feels Mercedes has 'finally found its North Star' with latest upgrade path",
    url: "https://www.racefans.net/hamilton-mercedes-finally-found-north-star/",
    publishedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    author: null,
    score: 72,
    comments: 31,
    engagementScore: 134
  },
  {
    id: "mock5",
    source: "reddit",
    sourceLabel: "r/formula1",
    sourceCategory: "hot",
    tier: "T2",
    weight: 0.75,
    title: "Paddock Rumours: Carlos Sainz reportedly close to finalizing Audi-Sauber multi-year deal",
    url: "https://www.reddit.com/r/formula1/comments/sainz_audi_sauber_deal_rumours/",
    publishedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    author: "F1Insider2026",
    score: 340,
    comments: 189,
    engagementScore: 718
  },
  {
    id: "mock6",
    source: "rss",
    sourceLabel: "Autosport",
    sourceCategory: "news",
    tier: "T1",
    weight: 1.25,
    title: "FIA confirms minor tweak to 2026 engine regulations to balance electrical deployment",
    url: "https://www.autosport.com/f1/news/fia-2026-engine-regulations-electrical-deployment/",
    publishedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    author: null,
    score: 90,
    comments: 24,
    engagementScore: 138
  },
  {
    id: "mock7",
    source: "reddit",
    sourceLabel: "r/F1Technical",
    sourceCategory: "hot",
    tier: "T1.5",
    weight: 1.0,
    title: "Why Red Bull is struggling with curb-riding: An layout analysis of their front suspension geometry",
    url: "https://www.reddit.com/r/F1Technical/comments/why_red_bull_struggles_curb_riding/",
    publishedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    author: "SuspensionGuru",
    score: 185,
    comments: 67,
    engagementScore: 319
  },
  {
    id: "mock8",
    source: "rss",
    sourceLabel: "The Race",
    sourceCategory: "news",
    tier: "T1",
    weight: 1.25,
    title: "How Norris is adapting his driving style to match Piastri's high-speed cornering rotation",
    url: "https://the-race.com/formula-1/norris-adapting-driving-style-piastri-rotation/",
    publishedAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    author: null,
    score: 110,
    comments: 48,
    engagementScore: 206
  },
  {
    id: "mock9",
    source: "reddit",
    sourceLabel: "r/formula1",
    sourceCategory: "new",
    tier: "T2",
    weight: 0.75,
    title: "Toto Wolff hints Mercedes could make surprise driver announcement before summer break",
    url: "https://www.reddit.com/r/formula1/comments/toto_wolff_mercedes_driver_announcement/",
    publishedAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    author: "SilverArrowsFan",
    score: 155,
    comments: 73,
    engagementScore: 301
  },
  {
    id: "mock10",
    source: "rss",
    sourceLabel: "RaceFans",
    sourceCategory: "news",
    tier: "T1.5",
    weight: 1.0,
    title: "Alonso criticizes race stewards over lack of consistency in track limits penalisation",
    url: "https://www.racefans.net/alonso-slams-stewards-track-limits/",
    publishedAt: new Date(Date.now() - 3600000 * 35).toISOString(),
    author: null,
    score: 98,
    comments: 59,
    engagementScore: 216
  }
];
